export const SAVE_POST_BEGIN = "FETCH_CATEGORY_BEGIN";
export const SAVE_POST_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const SAVE_POST_FAILURE = "FETCH_CATEGORY_FAILURE";
export const UPLOAD_IMAGE_BEGIN = "FETCH_CATEGORY_BEGIN";
export const UPLOAD_IMAGE_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const UPLOAD_IMAGE_FAILURE = "FETCH_CATEGORY_FAILURE";
