version: 2
updates:
- package-ecosystem: gomod
  directory: "/backend"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
    - 3.9.1
  - dependency-name: next
    versions:
    - 10.0.6
    - 10.0.7
    - 10.0.8
    - 10.1.3
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: rich-markdown-editor
    versions:
    - 11.1.6
    - 11.3.0
    - 11.3.1
    - 11.3.2
    - 11.4.1
    - 11.5.0
    - 11.6.1
    - 11.6.2
    - 11.6.3
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.1
  - dependency-name: husky
    versions:
    - 5.1.3
    - 5.2.0
  - dependency-name: react-burger-menu
    versions:
    - 3.0.3
    - 3.0.4
  - dependency-name: next-pwa
    versions:
    - 5.0.5
  - dependency-name: yup
    versions:
    - 0.32.8
  - dependency-name: dateformat
    versions:
    - 4.5.0
