version: '3.4'

services:
    ################################################################################
    ##                                  API
    ################################################################################
    api:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: bearpost_api
        working_dir: /go/src/github.com/alanqchen/bear-post
        command: go run main.go
        ports: 
            - 8080:8080
        environment: 
            - GOPATH=/go
        networks:
            - bearpost_network
        volumes: 
            - bearpost_api_data:/go/src
    ################################################################################
    ##                               PostgreSQL
    ################################################################################
    postgre:
        image: bearpost/postgre:latest
        container_name: bearpost_postgre
        restart: always
        ports:
            - 5432:5432
        labels:
            - "com.centurylinklabs.watchtower.enable=true"
        volumes: 
            - bearpost_postgre_data:/var/lib/postgresql/data
        networks: 
            - bearpost_network
    
    ################################################################################
    ##                                 Redis
    ################################################################################
    redis:
        image: bearpost/redis:latest
        container_name: bearpost_redis
        ports: 
            - 6379:6379
        labels:
            - "com.centurylinklabs.watchtower.enable=true"
        volumes: 
            - bearpost_redis_data:/data
        networks: 
            - bearpost_network

volumes:
    bearpost_postgre_data:
        driver: local
    bearpost_api_data:
        driver: local
    bearpost_redis_data:
        driver: local

networks:
    bearpost_network:
        driver: bridge