################################################################################
##            THIS IS FOR GITHUB ACTIONS (DON'T COPY THIS)
################################################################################

version: '3.8'

services:
    ################################################################################
    ##                                  API
    ################################################################################
    api-dev:
        build: backend/.
        container_name: bearpost_api_dev
        restart: unless-stopped
        ports: 
            - 8080:8080
        environment: 
            - GOPATH=/go
        depends_on: 
            - postgres
            - redis
        volumes: 
            - ./backend/config/app-docker.json:/bearpost/backend/config/app-custom.json
        networks:
            - bearpost_default

    ################################################################################
    ##                               Frontend
    ################################################################################
    frontend-dev:
        build:
            context: frontend/.
            network: host
        container_name: bearpost_frontend_dev
        restart: unless-stopped
        ports:
            - 3000
        depends_on:
            - api-dev
        networks:
            - bearpost_default

    ################################################################################
    ##                               PostgreSQL
    ################################################################################
    postgres:
        image: postgres:12.7
        container_name: bearpost_postgres_dev
        restart: always
        environment:
            POSTGRES_USER: bearpost
            POSTGRES_PASSWORD: bearpost
            POSTGRES_DB: bearpost
        ports:
            - 5432
        volumes: 
            - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks: 
            - bearpost_default
    
    ################################################################################
    ##                                 Redis
    ################################################################################
    redis:
        image: redis:latest
        container_name: bearpost_redis_dev
        command: redis-server --requirepass bearpost
        ports: 
            - 6379
        networks: 
            - bearpost_default
        sysctls:
            net.core.somaxconn: '511'

networks:
    bearpost_default:
