version: '3.4'

services:
    ################################################################################
    ##                                  API
    ################################################################################
    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: bearpost_api
        working_dir: /go/src/github.com/alanqchen/bear-post
        restart: unless-stopped
        command: go run main.go
        ports: 
            - 8080:8080
        environment: 
            - GOPATH=/go
            - REDIS_URL: redis:6379
        depends_on: 
            - postgre
            - redis
        networks:
            - api_network
        volumes: 
            - bearpost_api_data:/go/src
    ################################################################################
    ##                               PostgreSQL
    ################################################################################
    postgre:
        image: postgre
        env_file: 
            - postgre.env
        container_name: bearpost_postgre
        restart: always
        ports:
            - 5432:5432
        volumes: 
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - bearpost_postgre_data:/var/lib/postgresql/data
        networks: 
            - postgre_network
    
    ################################################################################
    ##                                 Redis
    ################################################################################
    redis:
        image: redis:apline
        container_name: bearpost_redis
        ports: 
            - 6379:6379
        volumes: 
            - bearpost_redis_data:/data
        networks: 
            - redis_network

volumes:
    bearpost_postgre_data:
        driver: local
    bearpost_api_data:
        driver: local
    bearpost_redis_data:
        driver: local

networks:
    api_network:
    postgre_network:
    redis_network:
    