version: '3.4'

services:
    ################################################################################
    ##                                  API
    ################################################################################
    api:
        image: aqchen/bearpost-api
        container_name: bearpost_api
        restart: unless-stopped
        ports: 
            - 8080
        environment: 
            - GOPATH=/go
        depends_on: 
            - postgres
            - redis
        networks:
            - bearpost_default
        volumes: 
            - bearpost_api_data:/go/src
    ################################################################################
    ##                               Frontend
    ################################################################################
    frontend:
        image: aqchen/bearpost-frontend
        container_name: bearpost_frontend
        restart: unless-stopped
        ports:
            - 3000
        depends_on:
            - api
        networks:
            - bearpost_default
        volumes:
            - bearpost_frontend_data:/app
            - bearpost_frontend_data:/app/node_modules
            - bearpost_frontend_data:/app/.next
            
    ################################################################################
    ##                               PostgreSQL
    ################################################################################
    postgres:
        image: postgres:latest
        container_name: bearpost_postgres
        restart: always
        environment:
            POSTGRES_USER: bearpost
            POSTGRES_PASSWORD: bearpost
            POSTGRES_DB: bearpost # not recommend to change this
        ports:
            - 5432
        volumes: 
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - bearpost_postgres_data:/var/lib/postgresql/data
        networks: 
            - bearpost_default
    
    ################################################################################
    ##                                 Redis
    ################################################################################
    redis:
        image: redis:latest
        container_name: bearpost_redis
        command: redis-server --requirepass bearpost
        ports: 
            - 6379
        volumes: 
            - bearpost_redis_data:/data
        networks: 
            - bearpost_default
        sysctls:
            net.core.somaxconn: '511'
    
    ################################################################################
    ##                                 NGINX (WIP)
    ################################################################################
    # 
    #nginx: 
    #    image: nginx:latest
    #    container_name: bearpost_nginx
    #    environment:
    #        - ENV=production
    #        - APPLICATION_URL=http://ismydependencysafe
    #    volumes:
    #      - ./nginx.conf:/etc/nginx/nginx.conf
    #      - certificates:/etc/letsencrypt/
    
volumes:
    bearpost_postgres_data:
        driver: local
    bearpost_api_data:
        driver: local
    bearpost_redis_data:
        driver: local
    bearpost_frontend_data:
        driver: local
    bearpost_certificates:
        driver: local

networks:
    bearpost_default:
    

