version: '3.4'

services:
    ################################################################################
    ##                                  API
    ################################################################################
    api:
        image: aqchen/bearpost-api
        container_name: bearpost_api
        restart: unless-stopped
        ports: 
            - 8080
        environment: 
            - GOPATH=/go
        depends_on: 
            - postgres
            - redis
        networks:
            - bearpost_default
        volumes: 
            - bearpost_api_data:/go/src
    ################################################################################
    ##                               Frontend
    ################################################################################
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        container_name: bearpost_frontend 
        ports:
            - 3000:3000
        depends_on:
            - api
        volumes:
            - bearpost_frontend_data:/app
            - bearpost_frontend_data:/app/node_modules
            - bearpost_frontend_data:/app/.next
        networks:
            bearpost_default:
                aliases:
                    - bearpost_frontend
       
            
    ################################################################################
    ##                               PostgreSQL
    ################################################################################
    postgres:
        image: postgres:latest
        container_name: bearpost_postgres
        restart: always
        environment:
            POSTGRES_USER: bearpost
            POSTGRES_PASSWORD: bearpost
            POSTGRES_DB: bearpost # not recommend to change this
        ports:
            - 5432
        volumes: 
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - bearpost_postgres_data:/var/lib/postgresql/data
        networks: 
            - bearpost_default
    
    ################################################################################
    ##                                 Redis
    ################################################################################
    redis:
        image: redis:latest
        container_name: bearpost_redis
        command: redis-server --requirepass bearpost
        ports: 
            - 6379
        volumes: 
            - bearpost_redis_data:/data
        networks: 
            - bearpost_default
        sysctls:
            net.core.somaxconn: '511'

volumes:
    bearpost_postgres_data:
        driver: local
    bearpost_api_data:
        driver: local
    bearpost_redis_data:
        driver: local
    bearpost_frontend_data:
        driver: local

networks:
    bearpost_default:
    

