// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Image interface {
	IsImage()
}

type PageInfo struct {
	Total       int  `json:"total"`
	PerPage     int  `json:"perPage"`
	HasNextPage bool `json:"hasNextPage"`
}

type Post struct {
	ID           string     `json:"id"`
	FeatureImage *PostImage `json:"featureImage"`
	Title        string     `json:"title"`
	Subtitle     string     `json:"subtitle"`
	Slug         string     `json:"slug"`
	Body         string     `json:"body"`
	Category     *string    `json:"category"`
	Tags         []string   `json:"tags"`
	Author       *User      `json:"author"`
	CreatedAt    string     `json:"createdAt"`
	UpdatedAt    *string    `json:"updatedAt"`
	PublishedAt  *string    `json:"publishedAt"`
	Hidden       *bool      `json:"hidden"`
	Views        *int       `json:"views"`
	Featured     *bool      `json:"featured"`
}

type PostImage struct {
	ID         string  `json:"id"`
	PostID     string  `json:"postID"`
	ImageID    string  `json:"imageID"`
	Link       string  `json:"link"`
	DeleteHash *string `json:"deleteHash"`
	CreatedAt  string  `json:"createdAt"`
	Name       string  `json:"name"`
	Type       string  `json:"type"`
	UserID     *string `json:"userID"`
	Width      int     `json:"width"`
	Height     int     `json:"height"`
	Base64Blur string  `json:"base64Blur"`
}

func (PostImage) IsImage() {}

type Posts struct {
	Total    int       `json:"total"`
	Posts    []*Post   `json:"posts"`
	PageInfo *PageInfo `json:"pageInfo"`
}

type User struct {
	ID        string     `json:"id"`
	Name      *string    `json:"name"`
	Username  *string    `json:"username"`
	Email     *string    `json:"email"`
	Password  *string    `json:"password"`
	Admin     *bool      `json:"admin"`
	CreatedAt string     `json:"created_at"`
	UpdatedAt *string    `json:"updated_at"`
	UserImage *UserImage `json:"userImage"`
}

type UserImage struct {
	ID         string  `json:"id"`
	UserID     string  `json:"userID"`
	ImageID    string  `json:"imageID"`
	Link       string  `json:"link"`
	DeleteHash *string `json:"deleteHash"`
	CreatedAt  string  `json:"createdAt"`
	Name       string  `json:"name"`
	Type       string  `json:"type"`
	Width      int     `json:"width"`
	Height     int     `json:"height"`
	Base64Blur string  `json:"base64Blur"`
}

func (UserImage) IsImage() {}

type GetPostByID struct {
	PostID int `json:"postID"`
}

type GetPostBySlug struct {
	Slug string `json:"slug"`
}

type GetPosts struct {
	MaxID int `json:"maxID"`
}
