version: '3.8'

services:
    ################################################################################
    ##                                  API
    ################################################################################
    api:
        image: aqchen/bearpost-api
        container_name: blog_api
        restart: unless-stopped
        ports: 
            - 8080:8080
        environment: 
          VIRTUAL_HOST: ${VIRTUAL_HOST}
          LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
          LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
        depends_on: 
            - postgres
            - redis
        volumes: 
            - ${UPLOADS_DIR}:/bearpost/backend/public
            - ${PWD}/app-docker.json:/bearpost/backend/config/app-custom.json
        networks:
            - hostnet
            - backend

    ################################################################################
    ##                               PostgreSQL
    ################################################################################
    postgres:
        image: postgres:latest
        container_name: blog_postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: bearpost # If you change any of these, change them
            POSTGRES_PASSWORD: bearpost # in the .json config file as well
            POSTGRES_DB: bearpost
        expose:
            - "5432"
        volumes: 
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - ${LOCAL_POSTGRES_DIR}:/var/lib/postgresql/data
        networks:
            - backend

    ################################################################################
    ##                                 Redis
    ################################################################################
    redis:
        image: redis:latest
        container_name: blog_redis
        restart: unless-stopped
        command: redis-server --requirepass bearpost # Change this in the .json config as well
        expose: 
            - "6379"
        volumes: 
            - ${LOCAL_REDIS_DIR}:/data
        sysctls:
            net.core.somaxconn: '511'
        networks:
            - backend

volumes:
    bearpost_api_data:
        driver: local

networks:
    backend:
       external: false
       driver: bridge
    hostnet:
       external:
           name: ${NETWORK}
