export const FETCH_DASHBOARD_POSTS_BEGIN = 'FETCH_DASHBOARD_POSTS_BEGIN';
export const FETCH_DASHBOARD_POSTS_SUCCESS = 'FETCH_DASHBOARD_POSTS_SUCCESS';
export const FETCH_DASHBOARD_POSTS_FAILURE = 'FETCH_DASHBOARD_POSTS_FAILURE';
export const FETCH_DASHBOARD_POSTS_NO_MORE = 'FETCH_DASHBOARD_POSTS_NO_MORE';
export const FETCH_DASHBOARD_POSTS_SET_MINID = 'FETCH_DASHBOARD_POSTS_SET_MINID';
