version: '3.4'

services:
    ################################################################################
    ##                                  API
    ################################################################################
    api:
        image: aqchen/bearpost-api
        container_name: bearpost_api
        restart: unless-stopped
        ports: 
            - 8080
        environment: 
            - GOPATH=/go
        depends_on: 
            - postgres
            - redis
        networks:
            - default
        volumes: 
            - bearpost_api_data:/go/src
    ################################################################################
    ##                               PostgreSQL
    ################################################################################
    postgres:
        image: postgres:latest
        env_file: 
            - postgres.env
        container_name: bearpost_postgre
        restart: always
        environment:
            POSTGRES_USER: bearpost
            POSTGRES_PASSWORD: bearpost
            POSTGRES_DB: bearpost # not recommend to change this
        ports:
            - 5432
        volumes: 
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - bearpost_postgre_data:/var/lib/postgresql/data
        networks: 
            - default
    
    ################################################################################
    ##                                 Redis
    ################################################################################
    redis:
        image: redis:latest
        container_name: bearpost_redis
        ports: 
            - 6379
        volumes: 
            - bearpost_redis_data:/data
        networks: 
            - default
        sysctls:
            net.core.somaxconn: '511'

volumes:
    bearpost_postgre_data:
        driver: local
    bearpost_api_data:
        driver: local
    bearpost_redis_data:
        driver: local

networks:
    default:
    

