export const FETCH_CATEGORY_BEGIN = "FETCH_CATEGORY_BEGIN";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_FAILURE = "FETCH_CATEGORY_FAILURE";
export const FETCH_CATEGORY_NO_MORE = "FETCH_CATEGORY_NO_MORE";
export const FETCH_CATEGORY_NEW = "FETCH_CATEGORY_NEW";
export const FETCH_CATEGORY_SET_MINID = "FETCH_POSTS_SET_MINID";
