name: CI Development

on:
  push:
    branches: [ '*-dev', login-page ]

jobs:

  build:
    name: Build and Push to Dockerhub
    runs-on: ubuntu-latest
    env:
      working-directory: .
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build backend docker image and run
      run: |
        docker-compose up -d --build api-dev || docker-compose up -d --build api-dev
      working-directory: ${{ env.working-directory }}

    - name: Login to Docker Hub
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push frontend docker file (master pull request or non-master push)
      run: |
        echo "::set-env name=GITHUB_REF::${{ github.ref }}"
        echo "old GITHUB_REF is $GITHUB_REF"
        GITHUB_REF=$(echo $GITHUB_REF | sed -e "s#refs/heads/##g")
        echo "new GITHUB_REF is $GITHUB_REF"
        docker build --network="host" -t aqchen/bearpost-frontend:$GITHUB_REF frontend/
        docker push aqchen/bearpost-frontend
        
    - name: Build and push backend docker file (master pull request or non-master push)
      run: |
        echo "::set-env name=GITHUB_REF::${{ github.ref }}"
        echo "old GITHUB_REF is $GITHUB_REF"
        GITHUB_REF=$(echo $GITHUB_REF | sed -e "s#refs/heads/##g")
        echo "new GITHUB_REF is $GITHUB_REF"
        docker tag bear-post_api-dev:latest aqchen/bearpost-api:$GITHUB_REF
        docker push aqchen/bearpost-api
