name: CI Development

on:
  push:
    branches: [ '*-dev', login-page ]

jobs:

  build:
    name: Build and Push to Dockerhub
    runs-on: ubuntu-latest
    env:
      working-directory: .
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Set GitHub branch name
      run: |
        echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e "s#refs/heads/##g")" >> $GITHUB_ENV

    - name: Build backend docker image and run
      run: |
        docker-compose up -d --build api-dev || docker-compose up -d --build api-dev
      working-directory: ${{ env.working-directory }}

    - name: Login to Docker Hub
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push frontend docker file (master pull request or non-master push)
      run: |
        echo "Branch name is $BRANCH_NAME"
        docker build --network="host" -t aqchen/bearpost-frontend:$BRANCH_NAME frontend/
        docker push aqchen/bearpost-frontend:$BRANCH_NAME
        
    - name: Build and push backend docker file (master pull request or non-master push)
      run: |
        docker tag bear-blog-engine_api-dev:latest aqchen/bearpost-api:$BRANCH_NAME
        docker push aqchen/bearpost-api:$BRANCH_NAME
